---
version: '3'
services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:latest
    container_name: traefik-example
    restart: unless-stopped
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    environment:
      - TZ=America/New_York
      #- DUCKDNS_TOKEN=<token>
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      #- "8085:8080"
    volumes:
      # Listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Read the configuration files
      - ./traefik.yml:/etc/traefik/traefik.yml
      # Configuration for LetsEncrypt certificates
      #- /opt/docker/traefik/acme.json:/acme.json
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.test.lan`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  hello1:
    image: nginxdemos/hello
    container_name: hello1
    hostname: hello1
    restart: unless-stopped
    labels:
      - "traefik.http.routers.hello1.rule=Host(`hello1.test.lan`)"
      - "traefik.http.services.hello1.loadbalancer.server.port=80"

  hello2:
    image: nginxdemos/hello
    container_name: hello2
    hostname: hello2
    restart: unless-stopped
    labels:
      - "traefik.http.routers.hello2.rule=Host(`hello2.test.lan`)"
      - "traefik.http.services.hello2.loadbalancer.server.port=80"

  hello3:
    image: nginxdemos/hello
    container_name: hello3
    hostname: hello3
    restart: unless-stopped
    labels:
      - "traefik.http.routers.hello3-http.entrypoints=web"
      - "traefik.http.routers.hello3-http.rule=Host(`hello3.test.lan`)"
      - "traefik.http.routers.hello3-http.middlewares=hello3-https"
      - "traefik.http.routers.hello3.entrypoints=websecure"
      - "traefik.http.routers.hello3.rule=Host(`hello3.test.lan`)"
      - "traefik.http.routers.hello3.tls=true"
      - "traefik.http.middlewares.hello3-https.redirectscheme.scheme=https"
      - "traefik.http.services.hello3.loadbalancer.server.port=80"